services:
  mongo:
    image: mongo:7
    container_name: worktrack-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - worktrack_mongo_data:/data/db

volumes:
  worktrack_mongo_data:
